apps/dashboard/urls.py
from django.urls import path, include

from . import views

app_name = "dashboard"
urlpatterns = [
    path(
        "dashboard/",
        views.DashboardView.as_view(template_name="dashboard/landing.html"),
        name="landing",
    ),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from .api import api

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", TemplateView.as_view(template_name="home.html"), name="home"),
    path("", include("apps.dashboard.urls")),
    path("api/", api.urls),
]

apps/dashboard/models.py
from django.db import models
from django.utils import timezone


class TodoManager(models.Manager):
    def to_list(self):
        todos = self.get_queryset()
        return [todo.to_json() for todo in todos]


class Todo(models.Model):
    STATUS_CHOICES = [
        ("done", "done"),
        ("outstanding", "outstanding"),
    ]
    detail = models.CharField(max_length=500)
    created = models.DateField(default=timezone.now, null=False)
    status = models.CharField(
        max_length=100, null=True, blank=True, choices=STATUS_CHOICES
    )
    updated = models.DateField(default=timezone.now, null=False)

    objects = TodoManager()

    def to_json(self):

        return {
            "created": self.created.strftime("%Y-%m-%d"),
            "detail": self.detail,
            "status": self.status,
        }

apps/dashboard/views.py
from django.utils import timezone
from django.views.generic import TemplateView


class DashboardView(TemplateView):
    def get_context_data(self, **kwargs):

        context = super().get_context_data(**kwargs)
        context.update({"chart_data": self.get_chart_data()})
        return context

    def get_chart_data(self):
        """return chart data"""
        return [
            {"value": 335, "name": "Direct"},
            {"value": 310, "name": "Email"},
            {"value": 274, "name": "Union Ads"},
            {"value": 235, "name": "Video Ads"},
            {"value": 400, "name": "Search Engine"},
        ]

templates/base.html
{% load static i18n %}
<!DOCTYPE html>
{% get_current_language as language_code %}

<html lang="{{ language_code }}">

<head>
  <title>{% spaceless %}{% block title %}Home{% endblock %}{% endspaceless %} </title>
  <meta charset="UTF-8">
  <meta name="msapplication-TileColor" content="#da532c">
  <meta name="theme-color" content="#ffffff">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  {# site meta and seo meta tags, override on specific pages as necessary. #}

  {% block site_meta %}{% endblock %}
  {% block seo-meta %}
    <meta name="robots" content="index,follow">
  {% endblock %}

  {% block extra_css %}{% endblock %}
  {% block head_js %}{% endblock %}

<link href="{% static 'css/site.css' %}" rel="stylesheet" type="text/css" />

  <link href="https://cdn.jsdelivr.net/npm/daisyui@1.16.1/dist/full.css" rel="stylesheet" type="text/css" />
  <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2/dist/tailwind.min.css" rel="stylesheet" type="text/css" />


  {# Alpine and app scripts #}
  <script defer src="https://unpkg.com/alpinejs@3.x.x/dist/cdn.min.js"></script>  


</head>

<body id="id-body" class="{{theme}}">
<div>
  <div class="flex h-screen antialiased overflow-x-hidden bg-base-200 text-base-content">

    <div class="{% block page_wrapper_class %}h-full w-full overflow-hidden fixed{% endblock %}">
      {# content goes here #}
      {% block content %}{% endblock %}


    </div>
  </div>
</div>
{% block footer_js %}

  <script type="text/javascript" src="{% static 'js/cookie.js' %}"></script>
  <script src="https://unpkg.com/swagger-client"></script>
  <script>
    // Cookie func
    const csrftoken = getCookie('csrftoken');
    const authHeaders = {'X-CSRFToken': csrftoken}

    // the application uses the swagger js client to interact with the api
    // if you are building a separate frontend, consult the docs on how to generate a client in typescript
    const client = SwaggerClient('/api/schema/', {
      requestInterceptor: (req) => {
        req.headers['X-CSRFToken'] = csrftoken;
        req.headers['Content-Type'] = 'application/json';
        return req;
      },
    })

    //uncomment to log api endpoints to console for debugging purposes
    client.then(client => console.log(client.apis))

   
  </script>

{% endblock %}

</body>
</html>

templates/components/header.html
{% load static %}
<section class="pb-20">
  <nav class="container px-4 mx-auto pt-12 flex justify-between items-center py-8 px-4 xl:px-10 ">
      <div class="flex flex-row">
          {% include "components/logo.html" %}
          <span class="text-2xl font-semibold mt-2 ml-3">Advantch Tutorials</span>
    </div>
    <div class="lg:hidden">
      <button class="navbar-burger flex items-center p-3 hover:bg-gray-50 rounded">
        <svg class="block h-4 w-4" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
          <title>Mobile menu</title>
          <path d="M0 3h20v2H0V3zm0 6h20v2H0V9zm0 6h20v2H0v-2z"></path>
        </svg>
      </button>
    </div>
    <ul class="hidden lg:flex lg:ml-auto lg:mr-12 lg:items-center lg:w-auto lg:space-x-12">
      <li><a class="text-sm font-medium" href="#">About</a></li>
      <li><a class="text-sm font-medium" href="#">Company</a></li>
    </ul>
    <div class="hidden lg:block"><a class="btn btn-sm btn-secondary" href="{% url 'dashboard:landing' %}">Login</a></div>
  </nav>
  <div class="container px-4 mx-auto pt-12">
    <div class="flex flex-wrap items-center -mx-4">
      <div class="w-full md:w-1/2 px-4 mb-6 md:mb-0">
        <span class="font-semibold text-xs text-blue-400">Django , TailwindCSS &amp; Alpine JS,</span>
        <h2 class="mt-8 mb-6 lg:mb-12 text-4xl lg:text-5xl font-semibold">AlpineJS Demo</h2>
        <div class="max-w-lg mb-6 lg:mb-12">
          <p class="text-xl text-gray-500">Django, Alpine, Javascript a match made in  heaven</p>
        </div>
        <div class="flex flex-wrap">
            <a class="btn btn-primary" href="{% url 'dashboard:landing' %}">Checkout the dashboard</a>
            <a class="btn btn-secondary btn-outline ml-2" href="#">Learn More</a></div>
      </div>
      <div class="relative w-full md:w-1/2 px-4">
        <img class="hidden lg:block top-0 right-0 z-10 lg:mt-28" src="{% static 'images/landing.svg' %}" alt="">
      </div>
    </div>
  </div>
  <div class="hidden navbar-menu fixed top-0 left-0 bottom-0 w-5/6 max-w-sm z-50">
    <div class="navbar-backdrop fixed inset-0 bg-gray-800 opacity-25"></div>
    <nav class="relative flex flex-col py-6 px-6 w-full h-full bg-white border-r overflow-y-auto">
      <div class="flex items-center mb-8">
        <a class="mr-auto text-lg font-semibold leading-none" href="#">
          <img class="h-7" src="zeus-assets/logo/logo-zeus-red.svg" alt="" width="auto">
        </a>
        <button class="navbar-close">
          <svg class="h-6 w-6 text-gray-500 cursor-pointer hover:text-gray-500" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"></path>
          </svg>
        </button>
      </div>
      <div>
        <ul>
          <li class="mb-1"><a class="block p-4 text-sm font-medium text-gray-900 hover:bg-gray-50 rounded" href="#">About</a></li>
          <li class="mb-1"><a class="block p-4 text-sm font-medium text-gray-900 hover:bg-gray-50 rounded" href="#">Company</a></li>
        </ul>
      </div>
      <div class="mt-auto">
        <div class="pt-6"><a class="block py-3 text-center text-sm leading-normal bg-red-50 hover:bg-red-100 text-red-300 font-semibold rounded transition duration-200" href="#">Login</a></div>
        <p class="mt-6 mb-4 text-sm text-center text-gray-500">
          <span>© 2021 All rights reserved.</span>
        </p>
      </div>
    </nav>
  </div>
</section>

templates/components/logo.html
      <a class="flex-shrink-0 text-2xl text-white font-semibold" href="{% url 'home' %}">
       <span class="shadow-xl text-primary"><svg xmlns="http://www.w3.org/2000/svg" class="h-12 w-12" viewBox="0 0 20 20" fill="currentColor">
  <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zM7 9a1 1 0 100-2 1 1 0 000 2zm7-1a1 1 0 11-2 0 1 1 0 012 0zm-.464 5.535a1 1 0 10-1.415-1.414 3 3 0 01-4.242 0 1 1 0 00-1.415 1.414 5 5 0 007.072 0z" clip-rule="evenodd" />
</svg><span>
      </a>

templates/dashboard/components/charts.html
<div class="border mockup-window border-base-300 chart-container">
    <div id='chartArea' style="width:600px; height:400px"></div>
</div>

templates/dashboard/components/todo.html
<div class="overflow-x-auto shadow-lg">
	<table class="table w-full">
		<thead>
			<tr>
				<th></th>
				<th>Date</th>
				<th>Detail</th>
				<th>Status</th>
				<th>Action</th>
			</tr>
		</thead>
		<tbody>
			<template x-for='(todo, index) in data.todo.list' :key='index'>
				<tr>
					<th x-text='`${index +1}`'></th>
					<td x-text='todo.date'></td>
					<td x-text='todo.detail'></td>
					<td x-text='todo.status'></td>
					<td>
						<div class="flex flex-row">
							<span class="mx-2"><svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
                <path fill-rule="evenodd" d="M9 2a1 1 0 00-.894.553L7.382 4H4a1 1 0 000 2v10a2 2 0 002 2h8a2 2 0 002-2V6a1 1 0 100-2h-3.382l-.724-1.447A1 1 0 0011 2H9zM7 8a1 1 0 012 0v6a1 1 0 11-2 0V8zm5-1a1 1 0 00-1 1v6a1 1 0 102 0V8a1 1 0 00-1-1z" clip-rule="evenodd" />
                 </svg>
                </span>

                 <span class="mx-2">
                    <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
                    <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clip-rule="evenodd" />
                    </svg>
                </span>
            </div>
        </td> 
      </tr>
    </template>  
    </tbody>
  </table>
</div>

templates/dashboard/landing.html
{% extends 'dashboard/layout.html' %}{% load static %} {% block dashboard_content %}
<div x-data='dashboard()' class="flex flex-col">
	<div class="w-full lg:max-w-7xl flex justify-between align-items-center mt-10 p-2 lg:px-6">
		<div class="text-lg md:text-3xl font-bold breadcrumbs">
			<ul>
				<li>
					<a @click="changeView('index')">Dashboard</a>
				</li>
				<li x-show="activeView.key !== 'index' ">
					<a x-text="activeView.name"></a>
				</li>
			</ul>
		</div>

		<a x-show="activeView.key !== 'index'" x-cloak @click="changeView('index')" class="btn btn-primary btn-sm mt-2">
			<svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
				<path fill-rule="evenodd" d="M9.707 14.707a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414l4-4a1 1 0 011.414 1.414L7.414 9H15a1 1 0 110 2H7.414l2.293 2.293a1 1 0 010 1.414z"
				 clip-rule="evenodd" />
			</svg>
			<span>Back</span>
    </a>
   
    </div>
	

	<div class="p-6 lg:max-w-7xl mt-6 mb-20">
		<div x-show="activeView.key === 'index'" class="grid grid-cols-2 gap-10 xl:grid-cols-5">
			<template x-for="(app, index) in apps" :key="app.name">
				<div @click="changeView(app.key)" class="card side bg-base-100 compact shadow dark:shadow-lg hover:shadow-xl bordered pointer">
					<div class="flex flex-col justify-start p-4 text-primary ">
						<div class="flex flex-row mx-auto">
							<img :src="app.icon" height="24" width="24"/>
                    <h2 class="text-lg text-base-content ml-3 font-bold" x-text="app.name"></h2>
                </div>
            
            </div>
            </div>
        </template>
        </div>

        <div x-show="activeView.key == 'chart'" x-cloak>
        {% include "dashboard/components/charts.html" %}
        </div>

        <div x-show="activeView.key == 'todo'" x-cloak>
        {% include "dashboard/components/todo.html" %}
        </div>

    </div>
</div>

{% endblock %}

{% block footer_js %}
  {{ block.super }}

  <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/echarts@5.0.2/dist/echarts.min.js"></script>

  {# load any variables required by our scripts that have to be rendered using django templates #}

  {{chart_data|json_script:"chartData"}} {# backend provided json data#}
  <script>
    const listIconUrl = "{% static "icons/list.svg" %}"
    const chartIconUrl = "{% static "icons/list.svg" %}"
  </script>

  <script type="text/javascript" src="{% static 'js/charts.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/dashboard.js' %}"></script>

{% endblock %}

templates/dashboard/layout.html
{% extends 'base.html' %} 
{% block content %}
<div class="flex flex-col">
	<section>
		<nav class="relative">
			<div class="p-6 flex items-center bg-base-100 shadow">
				{% include "components/logo.html" %}
				<ul class="hidden lg:flex">
					<li>
						<a class="flex ml-10 mr-10 items-center text-gray-600 hover:text-gray-800 text-sm" href="/">
							<svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
								<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 12l2-2m0 0l7-7 7 7M5 10v10a1 1 0 001 1h3m10-11l2 2m-2-2v10a1 1 0 01-1 1h-3m-6 0a1 1 0 001-1v-4a1 1 0 011-1h2a1 1 0 011 1v4a1 1 0 001 1m-6 0h6"
								/>
							</svg>
							<span class="ml-2 font-semibold">Home</span>
          </a>
        </li>
        <li>
          <a class="flex mr-10 items-center text-gray-600 hover:text-gray-800  text-sm" href="#">
              <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
  <path d="M5 3a2 2 0 00-2 2v2a2 2 0 002 2h2a2 2 0 002-2V5a2 2 0 00-2-2H5zM5 11a2 2 0 00-2 2v2a2 2 0 002 2h2a2 2 0 002-2v-2a2 2 0 00-2-2H5zM11 5a2 2 0 012-2h2a2 2 0 012 2v2a2 2 0 01-2 2h-2a2 2 0 01-2-2V5zM14 11a1 1 0 011 1v1h1a1 1 0 110 2h-1v1a1 1 0 11-2 0v-1h-1a1 1 0 110-2h1v-1a1 1 0 011-1z" />
</svg>
            <span class="ml-2 font-semibold">Dashboard</span>
          </a>
        </li>
      </ul>
      <ul class="hidden xl:flex lg:justify-end lg:items-center lg:space-x-6 mr-6 ml-auto">
        <li>
          <a class="text-gray-600 hover:text-gray-500" href="#">
         
          </a>
        </li>
        <li>
          <a class="text-gray-600 hover:text-gray-500" href="#">
           
          </a>
        </li>
      </ul>
      <div class="hidden lg:block">
        <button class="flex items-center">
          <div class="mr-3">
            <p class="text-sm text-gray-800">Sammy Harris</p>
            <p class="text-sm text-gray-600">Developer</p>
          </div>
          <div class="mr-2">
            <img class="w-10 h-10 rounded-full object-cover object-right" src="https://images.unsplash.com/photo-1635902549184-cf89a051e463?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=715&q=80" alt="photo">
          </div>
          <span>
           
          </span>
        </button>
      </div>
      <div class="ml-auto flex lg:hidden">
        <button class="navbar-burger flex items-center rounded focus:outline-none">
          <svg class="text-white bg-indigo-500 hover:bg-indigo-600 block h-8 w-8 p-2 rounded" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg" fill="currentColor">
            <title>Mobile menu</title>
            <path d="M0 3h20v2H0V3zm0 6h20v2H0V9zm0 6h20v2H0v-2z"></path>
          </svg>
        </button>
      </div>
    </div>
  </nav>
</section>

{% block dashboard_content %}  
  

  
{% endblock %}
</div>
{% endblock content %}

templates/home.html
{% extends 'base.html' %}

{% block content %}
    {% include "components/header.html" %}
{% endblock %}